server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taco_cloud
    username: root
    password: 1356
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    tacos: info
    org.springframework.security: ERROR
    org.hibernate: debug
  file:
    path: /var/logs/
    name: Taco_Cloud.log
taco:
  orders:
    pageSize: 20
---
spring:
  profiles: prod
  thymeleaf:
    cache: true
  jpa:
    database: mysql
    show-sql: false
logging:
  level:
    root: warn
    org.springframework.security: WARN
server:
  port: 8080
taco:
  orders:
    pageSize: 20
